### ISSUE TITLE
Visualization of land boundaries

### ISSUE THREAD

**Issue by mschmitz2** [NREL/SolarPILOT#19]
See images below. The first image correctly shows the default land boundaries (-180° to °180°) with the correct radial limits. 
For the second image, the land boundaries have been changed to (-175°,+180°). However, the plot shows them as if they were (-180°,-175°). 

![-180_ 180](https://user-images.githubusercontent.com/38347746/38742646-6faf9a30-3f3d-11e8-9923-6f2742ce79b2.PNG)

![-175_ 180](https://user-images.githubusercontent.com/38347746/38742644-6f93f91a-3f3d-11e8-968d-29cc99093824.PNG)

Conversely, the land boundaries for (-180°,-175°) are plotted as (-175°,+180°) (not shown).

This error only appears in the 'Land Boundaries' plot; heliostats are positioned correctly according to the desired land boundaries.

**Comment by mjwagner2** [comment]
@mschmitz2 I've also confirmed this issue. The relevant code is in app/FieldPlot.cpp, lines 370-387. It appears the arc points are drawn in reverse order. I'm adding a fix for this and will put it in the next patch release.

**Comment by mschmitz2** [comment]
@mjwagner2 cool! Thanks!
