### ISSUE TITLE
Cosine overwitten by intercept in _detail_results

### ISSUE THREAD

**Issue by davidagross** [NREL/SolarPILOT#26]
Just found this in the text while browsing the source for intercept calculation methods.

https://github.com/NREL/SolarPILOT/blob/develop/app/scripting.cpp#L709

```
            p.hash_item( "cosine", H->getEfficiencyIntercept() );
            p.hash_item( "intercept", H->getEfficiencyIntercept() );
```

**Comment by mjwagner2** [comment]
Thanks @davidagross, good catch. I'll correct this in the next patch release. The revised code is included in a commit [here](https://github.com/NREL/SolarPILOT/commit/635fa0a08143f5de446af85719ddb7152f068788).
